In [1]:
import numpy as np

inputing the matrices

In [8]:
def get_matrix(r, c) -> list:
    matrix = list()
    for i in range(0, r):
        row = list()
        for j in range(0, c):
            e = int(input(f"m[{i}][{j}]: "))
            row.append(e)
        matrix.append(row)
    return matrix

r1, c1 = map(int, input("Enter the size of the first matrix").split())
r2, c2 = map(int, input("Enter the size of the second matrix").split())
if c1 != r2:
    print("Incompatible order")
else:
    m1 = np.array(get_matrix(r1, c1))
    m2 = np.array(get_matrix(r2, c2))
    print("First matrix:")
    print(m1)
    print("Second matrix:")
    print(m2)


First matrix:
[[1 2]
 [3 4]]
Second matrix:
[[1 2]
 [3 4]]


TRANSPOSE     TRACE

In [10]:

print("The transpose of matrix is: ")
print(np.transpose(m1))
print("The trace of matrix is: ")
print(np.trace(m1))


The transpose of first matrix is: 
[[1 3]
 [2 4]]
The trace of first matrix is: 
5


DOT

In [12]:
print("The dot of the two matrices")
print(np.dot(m1,m2))

The dot of the two matrices
[[ 7 10]
 [15 22]]


INVERSE

In [13]:
print("Inverse of matrix is: \n", np.linalg.inv(m1))

Inverse of first matrix is: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


RANK

In [16]:
print("Rank of matrix is ", np.linalg.matrix_rank(m1))

Rank of first matrix is  2


Eigen val and vector

In [17]:
eigval, eigvec = np.linalg.eig(m1)
print("The eigen value is: ")
print(eigval)
print("The eigen vectors are: ")
print(eigvec)

The eigen value is: 
[-0.37228132  5.37228132]
The eigen vectors are: 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


DETERMINANT

In [18]:
print("The determinant is: ")
print(np.linalg.det(m1))

The determinant is: 
-2.0000000000000004
