importing the libraries

In [1]:
import numpy as np

pgm 1

In [ ]:
n = int(input("How many values? "))
arr = np.array([])
for i in range(n):
    arr = np.append(arr, int(input(f"a[{i}]: ")))
print("The converted temp are: ")
for i in arr:
    f = i
    c = (f - 32) * ( 5 / 9 )
    print(f, " -> ", c)

pgm 2

In [ ]:
arr = np.random.randint(0, 100, 1000)
print(f"Average: {np.average(arr):.2f}")
print(f"Variance: {np.var(arr):.2f}")
print(f"Standard Deviation: {np.std(arr):.2f}")

pgm 3

In [ ]:
n = int(input("How many values? "))
arr = np.array([[]])
for i in range(n):
    arr = np.append(arr, [int(input(f"a[{i}]: "))])
for i in arr:
    print(f"{i}degree -> {np.deg2rad(i):.2f}rad")

pgm 4

In [ ]:
arr = np.random.randint(0, 100, 5)
n = np.diff(arr)
print(arr)
print(n)

pgm 5

In [6]:
comp = np.array([4 + 2j, 3 - 4j, 6 + 1j])
print("Before sorting: ")
print(*comp)
print("After sorting: ")
print(*np.sort_complex(comp))

Before sorting: 
(4+2j) (3-4j) (6+1j)
After sorting: 
(3-4j) (4+2j) (6+1j)


pgm 6

In [12]:
arr = np.random.randint(0, 10, 5)
print("The random array: ",arr)
print("Elements greater than 4: ",*arr[np.where(arr>4)])

The random array:  [3 7 3 8 0]
Elements greater than 4:  7 8


pgm 7

In [18]:
arr = np.random.randint(0, 10, 5)
print(*arr)
n = int(input("Enter the element to search: "))
print(f"{n} found at {np.where(arr == n)}") if n in arr else print("not found")

8 4 4 4 3
4 found at (array([1, 2, 3]),)


pgm 8

In [29]:
arr = np.random.randint(0, 100, 5)
temp = np.savetxt("file.txt", arr)
temp = np.loadtxt("file.txt")
print("The data from text file is: ", temp)

The data from text file is:  [38. 89. 25. 31. 26.]


pgm 9

In [33]:
print("Even numbers from 30 to 60")
arr = np.arange(30, 61, 2)
print(*arr)

Even numbers from 30 to 60
30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60


pgm 10

In [43]:
arr = np.random.randint(0, 10, (5, 5))
print(arr)
print("Sum of all elements: ", np.sum(arr))
print("Sum along row: ", np.sum(arr, axis=0))
print("Sum along column: ", np.sum(arr, axis=1))

[[3 9 3 6 8]
 [2 8 5 2 6]
 [3 9 4 8 2]
 [7 1 5 0 9]
 [9 3 9 2 9]]
Sum of all elements:  132
Sum along row:  [24 30 26 18 34]
Sum along column:  [29 23 26 22 32]
